version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
      open-pull-requests-limit: 2
      labels:
          - type:dependencies
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope
